# Generated by Django 5.1.2 on 2024-10-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('firma', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=15)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('mesaj', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
