# Generated by Django 5.1.2 on 2024-10-14 18:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfa_contabilitate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfa',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
