# Generated by Django 5.2.3 on 2026-03-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfa_contabilitate', '0003_alter_pfa_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfa',
            name='firma_destinatie',
            field=models.CharField(blank=True, default='Consultant Fiscal - Gebaila Livia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pfa',
            name='telefon',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='pfa',
            unique_together={('data', 'ora')},
        ),
    ]
